version: "3"
services:
  db:
    build: .
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  
  pgamdin4:
    image: dpage/pgadmin4
    volumes: 
      - ./pgadmin4:/var/lib/pgadmin4
    ports: 
      - 80:80
    environment: 
      PGADMIN_DEFAULT_EMAIL: local@local.info
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on: 
      - db
